'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {evaluateDayTradeOutcome}=require('../lib/daytrade-outcome-evaluator');const {normalizeOutcomeRecord}=require('../lib/daytrade-outcome-contract');const {createOutcomeLogger,preflightOutcomeTree}=require('../lib/daytrade-outcome-logger');const {createLocalEvaluationLogger}=require('../lib/screener-evaluation-logger');
function initial(){return{schema_version:1,strategy:'DAY_TRADE',run_id:'run-1',run_mode:'MORNING_SCOUT',batch_index:0,scheduled_slot:'OPENING',scheduler_source:'test',code_sha:'a'.repeat(40),config_hash:'b'.repeat(64),ticker:'TEST',candidate_revision:1,observed_at:'2026-08-03T03:00:00.000Z',feature_as_of_ts:null,feature_as_of_provenance:'unavailable',data_source:'fixture',data_lag_ms:null,ohlcv_sofar:{open:100,high:101,low:99,close:100,volume:1,provenance:'fixture'},rvol_raw:1,rvol_seasonal:null,rvol_seasonal_provenance:'unavailable',score_components_raw:{momentum:1},score_components_provenance:'fixture',score_raw:88,score_display:88,status:'READY_BREAKOUT',passed:true,rejection_codes:[],gate_trace:{schema_version:1,rule_set_version:'test',gates:{}},levels:{raw:{entry_low:101.1,entry_high:102,stop_loss:98.9,tp1:105.1,tp2:110},normalized:null,provenance:'initial'},publication:{published:false,rank:null}};}
function policy(){const c=(name,rate=0)=>({version:name+'-v1',rate,fixed:0,provenance:'caller supplied synthetic policy'});return{policy_version:'synthetic-v1',currency:'IDR',tick:{version:'synthetic-tick-v1',size:1,entry_snap:'CEIL',stop_snap:'FLOOR',target_snap:'CEIL',provenance:'caller supplied synthetic ticks'},fees:c('fee',.001),taxes:c('tax',.002),spread:c('spread',.003),slippage:c('slippage',.004)};}
function bar(timestamp,low,high,close=102,ticker='TEST'){return{ticker,timestamp,open:close,high,low,close,provenance:'synthetic ordered bar',source_as_of:timestamp};}
function input(rows,extra={}){return{initial:initial(),observations:rows,policy:policy(),horizon_end:'2026-08-03T04:00:00.000Z',evidence_as_of:'2026-08-03T04:00:00.000Z',completed_at:'2026-08-03T04:01:00.000Z',...extra};}
test('unfilled expiration is distinct from a loss and has no return',()=>{const r=evaluateDayTradeOutcome(input([bar('2026-08-03T03:10:00.000Z',103,104,103)]));assert.equal(r.entry.state,'UNFILLED');assert.equal(r.touches.outcome,'EXPIRED');assert.equal(r.performance.net_r,null);assert.notEqual(r.touches.outcome,'SL_FIRST');});
test('fill then TP1 and fill then SL are deterministic',()=>{const tp=evaluateDayTradeOutcome(input([bar('2026-08-03T03:10:00.000Z',101,103),bar('2026-08-03T03:20:00.000Z',100,107,106)]));assert.equal(tp.entry.fill_price,102);assert.equal(tp.touches.outcome,'TP1_FIRST');assert.equal(tp.levels.tp1_snapped,106);const sl=evaluateDayTradeOutcome(input([bar('2026-08-03T03:10:00.000Z',101,103),bar('2026-08-03T03:20:00.000Z',97,103,98)]));assert.equal(sl.touches.outcome,'SL_FIRST');assert.ok(sl.performance.net_r<sl.performance.gross_r);});
test('same bar TP and SL is pessimistic SL-first',()=>{const r=evaluateDayTradeOutcome(input([bar('2026-08-03T03:10:00.000Z',97,107)]));assert.equal(r.touches.outcome,'SL_FIRST');assert.equal(r.touches.ordering_convention,'PESSIMISTIC_SL_FIRST');assert.equal(r.touches.tp1_at,r.touches.sl_at);});
test('filled and unfilled expiration remain distinguishable; incomplete evidence is explicit',()=>{const filled=evaluateDayTradeOutcome(input([bar('2026-08-03T03:10:00.000Z',101,103,103)]));assert.equal(filled.entry.state,'FILLED');assert.equal(filled.touches.outcome,'EXPIRED');assert.notEqual(filled.performance.net_return,null);const unresolved=evaluateDayTradeOutcome(input([],{evidence_as_of:'2026-08-03T03:30:00.000Z',completed_at:'2026-08-03T03:31:00.000Z'}));assert.equal(unresolved.entry.state,'UNRESOLVED');assert.equal(unresolved.touches.outcome,'UNRESOLVED');assert.deepEqual(unresolved.rejection_codes,['EVIDENCE_HORIZON_INCOMPLETE']);});
test('MFE MAE, tick snapping, and explicit costs are calculated',()=>{const r=evaluateDayTradeOutcome(input([bar('2026-08-03T03:10:00.000Z',100,103),bar('2026-08-03T03:20:00.000Z',99,105,104)]));assert.equal(r.levels.entry_snapped,102);assert.equal(r.levels.stop_snapped,98);assert.equal(r.excursions.mfe,3/102);assert.equal(r.excursions.mae,-3/102);assert.ok(Math.abs(r.performance.costs.total-.01)<1e-12);assert.ok(Math.abs(r.performance.net_return-(2/102-.01))<1e-12);});
test('malformed, duplicate, out-of-order, mixed ticker, and future evidence fail closed',()=>{const good=bar('2026-08-03T03:10:00.000Z',101,103);for(const rows of [[good,good],[bar('2026-08-03T03:20:00.000Z',101,103),good],[bar('2026-08-03T03:10:00.000Z',101,103,102,'OTHER')],[bar('2026-08-03T04:01:00.000Z',101,103)]])assert.throws(()=>evaluateDayTradeOutcome(input(rows)));assert.throws(()=>evaluateDayTradeOutcome(input([{...good,unexpected:true}])));});
test('strict schema, canonical hash, byte limits, and secret rejection',()=>{const r=evaluateDayTradeOutcome(input([]));assert.deepEqual(normalizeOutcomeRecord(r),r);assert.throws(()=>normalizeOutcomeRecord({...r,extra:true}),/exact keys/);assert.throws(()=>evaluateDayTradeOutcome(input([],{policy:{...policy(),tick:{...policy().tick,provenance:'https:\/\/secret.example'}}})),/secret-safe/);assert.throws(()=>normalizeOutcomeRecord({...r,record_hash:'0'.repeat(64)}),/hash mismatch/);});
function rootWithInitial(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'outcome-tree-'));const log=createLocalEvaluationLogger({root,env:{EVALUATION_LOGGING_ENABLED:'true'},runId:'run-1',marketDate:'2026-08-03',diskAudit:{writes_should_stop:false}});log.append(initial());log.finalize();return root;}
test('append-only outcome has checksum/manifest and duplicate finalization is rejected',()=>{const root=rootWithInitial(),record=evaluateDayTradeOutcome(input([])),before=fs.readFileSync(path.join(root,fs.readdirSync(path.join(root,'manifests','2026-08-03')).length?'manifests/2026-08-03/'+fs.readdirSync(path.join(root,'manifests','2026-08-03'))[0]:''));const m=createOutcomeLogger({root,record});assert.equal(m.initial_record_digest,record.initial_link.record_digest);assert.throws(()=>createOutcomeLogger({root,record}),/DUPLICATE_FINALIZATION/);assert.deepEqual(fs.readFileSync(path.join(root,'manifests','2026-08-03',fs.readdirSync(path.join(root,'manifests','2026-08-03'))[0])),before);});
test('whole-tree symlink/open/orphan/quarantine/unexpected/path escape fail before writer effects',()=>{for(const kind of ['symlink','open','orphan','quarantine','unexpected']){const root=rootWithInitial();if(kind==='symlink')fs.symlinkSync(os.tmpdir(),path.join(root,'outcomes'),'dir');if(kind==='open'){fs.mkdirSync(path.join(root,'outcomes'),{recursive:true});fs.writeFileSync(path.join(root,'outcomes','x.open.jsonl.gz'),'');}if(kind==='orphan'){fs.mkdirSync(path.join(root,'outcomes','x'),{recursive:true});fs.writeFileSync(path.join(root,'outcomes','x','x.jsonl.gz'),'x');}if(kind==='quarantine'){fs.mkdirSync(path.join(root,'outcome-quarantine'),{recursive:true});fs.writeFileSync(path.join(root,'outcome-quarantine','x'),'x');}if(kind==='unexpected')fs.writeFileSync(path.join(root,'surprise'),'x');const before=fs.readdirSync(root).sort();assert.throws(()=>preflightOutcomeTree({root}),/OUTCOME_PREFLIGHT_/);assert.deepEqual(fs.readdirSync(root).sort(),before,kind);}});
test('all validation and mapping can complete before logger creation and modules have no integrations',()=>{const record=evaluateDayTradeOutcome(input([]));let calls=0;const create=()=>{calls++;};assert.doesNotThrow(()=>normalizeOutcomeRecord(record));assert.equal(calls,0);create();assert.equal(calls,1);for(const file of ['lib/daytrade-outcome-contract.js','lib/daytrade-outcome-evaluator.js','lib/daytrade-outcome-logger.js']){const src=fs.readFileSync(path.join(__dirname,'..',file),'utf8');assert.doesNotMatch(src,/supabase|telegram|sector-hot|vercel\.app|global\.fetch|setInterval|setTimeout/i);}});
