'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fsp=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const momentum=require('../lib/intraday-fast-watcher-momentum');
const pool=require('../lib/intraday-fast-watcher-pool');
const publisher=require('../lib/intraday-fast-watcher-publisher');
const guarded=require('../lib/intraday-fast-watcher-guarded-live');
function obs(ticker,time,extra){return {ticker,scheduled_time:time,current_price:100,entry_low:98,entry_high:103,tp1:112,stop_loss:95,current_status:'EARLY_RADAR',volume:1000,average_volume:700,relative_volume:1.1,momentum_component:14,liquidity_component:16,risk_reward:1.7,high:103,low:98,freshness:{is_stale:false},...(extra||{})};}
test('volatility-relative momentum confirms a near-miss twice',()=>{const first=pool.process({sampleDate:'2026-07-31',scheduledTime:'09:10',shortlistRows:[{ticker:'PADA',source_rank:1}],observations:[obs('PADA','09:10')],priorState:null}); assert.equal(first.state.tickers.PADA.status,'WATCHING'); const second=pool.process({sampleDate:'2026-07-31',scheduledTime:'09:13',shortlistRows:[{ticker:'PADA',source_rank:1}],observations:[obs('PADA','09:13',{current_price:101,volume:1700,relative_volume:1.5})],priorState:first.state}); assert.equal(second.state.tickers.PADA.status,'READY_PENDING'); const third=pool.process({sampleDate:'2026-07-31',scheduledTime:'09:22',shortlistRows:[{ticker:'PADA',source_rank:1}],observations:[obs('PADA','09:22',{current_price:102,volume:3200,relative_volume:2})],priorState:second.state}); assert.equal(third.state.tickers.PADA.status,'READY_CONFIRMED'); assert.equal(third.publishable.length,1);});
test('candidate persists when missing from latest shortlist',()=>{const initial=pool.process({sampleDate:'2026-07-31',scheduledTime:'09:10',shortlistRows:[{ticker:'TLKM',source_rank:1}],observations:[obs('TLKM','09:10')],priorState:null}); const merged=pool.mergePayload({results:[{ticker:'BBRI'}]},initial.state,'09:13',[],20); assert.ok(merged.results.some(row=>row.ticker==='TLKM'));});
test('pool caps at 20 and publish caps at 3',()=>{const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'; const supplemental=Array.from({length:24},(_,i)=>({ticker:`A${letters[Math.floor(i/26)]}${letters[i%26]}A`,status:'EARLY_RADAR',daytrade_score:90-i})); const merged=pool.mergePayload({results:[{ticker:'BBRI'}]},null,'09:10',supplemental,20); assert.equal(merged.results.length,20); const ranked=pool.rankPublishable(Array.from({length:6},(_,i)=>({ticker:`BBR${i}`,publish_score:70+i,watch_score:80,shortlist_rank:i+1}))); assert.equal(ranked.length,3);});
test('hard guards still block stale stop and chase',()=>{assert.equal(momentum.evaluate(obs('BBRI','09:13',{freshness:{is_stale:true}}),{}).status,'STALE'); assert.equal(momentum.evaluate(obs('BBRI','09:13',{current_price:94}),{}).status,'INVALIDATED'); const tracker={first_price:100,last_price:100,last_volume:1000,last_observation_minute:550,in_latest_shortlist:true}; assert.equal(momentum.evaluate(obs('BBRI','09:13',{current_price:108,entry_high:110,tp1:120,volume:2000}),tracker).status,'BLOCKED_CHASE');});
test('system publication survives notification failure',async()=>{const root=await fsp.mkdtemp(path.join(os.tmpdir(),'fw-v2-')); const calls=[]; const storeClient={from(table){assert.equal(table,'daytrade_screener_latest'); return {upsert(rows){calls.push(rows); return {select:async()=>({data:rows,error:null})};}};}}; const result=await publisher.publishConfirmed({sampleDate:'2026-07-31',scheduledTime:'09:13',publishedDir:root,storeClient,notifyFn:async()=>({sent:false,reason:'timeout'}),env:{FAST_WATCHER_LIVE_ENABLED:'1',FAST_WATCHER_PUBLISH_ENABLED:'1',FAST_WATCHER_TELEGRAM_ENABLED:'1',FAST_WATCHER_TELEGRAM_CHAT_ID:'-1001'},publishable:[{ticker:'PADA',setup_id:'setup-1',ready_streak:2,watch_score:82,publish_score:88,observation:obs('PADA','09:13',{current_price:101,volume:1700,relative_volume:1.5,metrics:{price_change_pct:1}})}]}); assert.equal(calls.length,1); assert.equal(result.system_published,1); assert.equal(result.telegram_sent,0);});
test('guarded live kill switch defaults off',async()=>{const result=await guarded.run({sampleDate:'2026-07-31',scheduledTime:'09:10',env:{}}); assert.equal(result.status,'live_disabled');});
test('guarded orchestrator publishes only after second check',async()=>{const root=await fsp.mkdtemp(path.join(os.tmpdir(),'fw-orchestrator-')); let run=0; const fakeEngine={runDayTradeBatch:async batch=>({results:batch.map(item=>{run+=1; return {ticker:item.ticker,last_price:run===1?100:101,entry_low:98,entry_high:103,tp1:112,stop_loss:95,status:'EARLY_RADAR',daytrade_score:75,volume_today:run===1?1000:1800,avg_volume_20d:700,volume_ratio_20d:run===1?1.5:1.8,momentum_score:14,liquidity_score:16,risk_reward:1.7,high_price:103,low_price:98};}),failed:[]})}; const fakeCollector={checkProductionWorkerActive:async()=>({active:false}),fetchWithFreshnessFallback:async()=>({candles:[],freshness:{is_stale:false}}),buildCandidateRecord:(r,t)=>obs(r.ticker,t,{current_price:r.last_price,volume:r.volume_today,relative_volume:r.volume_ratio_20d,score:r.daytrade_score}),deriveDistances:r=>r,sanitizeRecord:r=>r}; const common={sampleDate:'2026-07-31',shortlistFile:'ignored',stateDir:path.join(root,'state'),eventDir:path.join(root,'events'),observationRoot:path.join(root,'obs'),publishedDir:path.join(root,'published'),env:{FAST_WATCHER_LIVE_ENABLED:'1',FAST_WATCHER_PUBLISH_ENABLED:'1'},readPayload:async()=>({status:'published',radar_candidates:['PADA']}),loadSupplemental:async()=>[],engine:fakeEngine,collector:fakeCollector,checkProductionWorkerActive:async()=>({active:false}),publishConfirmed:async()=>({system_published:1,telegram_sent:0})}; const first=await guarded.run({...common,scheduledTime:'09:10'}); assert.equal(first.system_published,0); const second=await guarded.run({...common,scheduledTime:'09:13'}); assert.equal(second.confirmed.length,1); assert.equal(second.system_published,1);});
