'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const http=require('node:http');const zlib=require('node:zlib');
const {createStaticResponder,encodingFor}=require('../lib/static-assets');
async function fixture(t,options={}){
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ac-static-'));const root=path.join(dir,'public');await fs.mkdir(root);await fs.writeFile(path.join(root,'app.js'),'const x="'+ 'payload '.repeat(500)+'";');await fs.writeFile(path.join(root,'index.html'),'<main>private</main>');await fs.writeFile(path.join(root,'data.json'),'{"not":"public cache"}');
 const serve=createStaticResponder({rootDir:root,mimeTypes:{'.js':'text/javascript','.html':'text/html','.json':'application/json'},...options});const server=http.createServer(async(req,res)=>{if(!await serve(req,res,req.url.split('?')[0])){res.statusCode=404;res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await new Promise(resolve=>server.close(resolve));await fs.rm(dir,{recursive:true,force:true});});
 const get=(name,headers={},method='GET')=>new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:server.address().port,path:name,headers,method},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});req.on('error',reject);req.end();});return {dir,root,serve,get};
}
test('negotiates supported encodings and quality/exclusions',()=>{for(const [h,want] of [['',null],['br,gzip','br'],['gzip;q=1,br;q=.2','gzip'],['br;q=0,gzip;q=0',null],['br;q=.4,identity;q=1',null],['*;q=0','unacceptable'],['br;q=invalid,gzip;q=1','gzip']])assert.equal(encodingFor(h),want,h);});
test('compressed representations roundtrip and repeated requests reuse reads/compression',async t=>{const x=await fixture(t);const raw=await x.get('/app.js');const results=await Promise.all(Array.from({length:12},()=>x.get('/app.js',{'accept-encoding':'gzip'})));for(const result of results){assert.equal(result.status,200);assert.deepEqual(zlib.gunzipSync(result.body),raw.body);}const br=await x.get('/app.js',{'accept-encoding':'br'});assert.deepEqual(zlib.brotliDecompressSync(br.body),raw.body);assert.equal(x.serve.stats().reads,1);assert.equal(x.serve.stats().compressions,2);});
test('mutable assets revalidate with ETag and do not retain stale version-query bytes',async t=>{const x=await fixture(t);const first=await x.get('/app.js?v=old');assert.equal(first.headers['cache-control'],'public, max-age=0, must-revalidate');let next=await x.get('/app.js',{'if-none-match':first.headers.etag});assert.equal(next.status,304);assert.equal(next.body.length,0);await fs.writeFile(path.join(x.root,'app.js'),'changed');next=await x.get('/app.js?v=old',{'if-none-match':first.headers.etag});assert.equal(next.status,200);assert.equal(next.body.toString(),'changed');assert.notEqual(next.headers.etag,first.headers.etag);});
test('HTML and JSON never become publicly cacheable or conditional-304',async t=>{const x=await fixture(t);for(const name of ['index.html','data.json']){const response=await x.get('/'+name,{'if-none-match':'*'});assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'private, no-store');assert.equal(response.headers.etag,undefined);}});
test('HEAD, method restrictions and unsupported encoding are explicit',async t=>{const x=await fixture(t);const h=await x.get('/app.js',{'accept-encoding':'gzip'},'HEAD');assert.equal(h.status,200);assert.equal(h.body.length,0);assert.equal(h.headers['content-encoding'],'gzip');assert.equal((await x.get('/app.js',{},'POST')).status,405);assert.equal((await x.get('/app.js',{'accept-encoding':'*;q=0'})).status,406);});
test('traversal, invalid encoding, hidden files and escaping symlinks are refused',async t=>{const x=await fixture(t);await fs.writeFile(path.join(x.dir,'secret'),'secret');await fs.writeFile(path.join(x.root,'.env'),'secret');await fs.symlink(path.join(x.dir,'secret'),path.join(x.root,'escape.js'));for(const url of ['/../secret','/%2e%2e/secret','/%00','/bad%ZZ','/.env','/escape.js']){const result=await x.get(url);assert.equal(result.status,404,url);assert.ok(!result.body.includes('secret'));}});
test('root symlink replacement follows a new atomic release',async t=>{const x=await fixture(t);const other=path.join(x.dir,'new');await fs.mkdir(other);await fs.writeFile(path.join(other,'app.js'),'new release');await fs.rename(x.root,path.join(x.dir,'old'));await fs.symlink(other,x.root);assert.equal((await x.get('/app.js')).body.toString(),'new release');});
test('LRU budget and streaming prevent unbounded cached files',async t=>{const x=await fixture(t,{maxBytes:150,maxEntries:1,maxFileBytes:5000});await x.get('/app.js');assert.ok(x.serve.stats().bytes<=150);await fs.writeFile(path.join(x.root,'large.js'),'x'.repeat(10000));const r=await x.get('/large.js');assert.equal(r.body.length,10000);assert.ok(x.serve.stats().bytes<=150);});
