'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path');
const session=require('../lib/admin-session'); const identity=require('../lib/subscription-identity'); const {getEntitlements,TRIAL_DURATION_HOURS}=require('../lib/entitlements');
const root=path.join(__dirname,'..'), migration=fs.readFileSync(path.join(root,'supabase','subscription-phase-2-migration.sql'),'utf8'), api=fs.readFileSync(path.join(root,'api','login-user.js'),'utf8');
test('Phase 5A pins a distinct 15-minute purpose-bound onboarding session',()=>{ const old=process.env.SESSION_SECRET;process.env.SESSION_SECRET='phase5a-test-secret';try { const token=session.createOnboardingSessionToken({userId:'u',username:'alice'}); assert.equal(session.getSession({headers:{cookie:'ac_sess='+token}}),null); assert.equal(session.verifyOnboardingSessionToken(token).valid,true); assert.match(session.buildOnboardingCookie(token),/HttpOnly; SameSite=Strict;(?: Secure;)? Max-Age=900/); assert.equal(session.ONBOARDING_MAX_AGE_SECONDS,900); } finally {if(old===undefined)delete process.env.SESSION_SECRET;else process.env.SESSION_SECRET=old;} });
test('trial is explicit, exactly ten elapsed days, and expires at the exclusive boundary',()=>{ assert.equal(TRIAL_DURATION_HOURS,240); assert.match(migration,/v_expiry:=v_start \+ interval '10 days'/); const row={source:'trial',status:'active',lifetime:false,starts_at:'2026-01-01T00:00:00Z',expires_at:'2026-01-11T00:00:00Z'}; assert.equal(getEntitlements({}, {username:'alice'},[row],new Date('2026-01-10T23:59:59.999Z')).premium,true); assert.equal(getEntitlements({}, {username:'alice'},[row],new Date('2026-01-11T00:00:00Z')).premium,false); });
test('activation RPC locks identity, permanently reserves Telegram identity, and is service-only',()=>{ for(const x of ['activate_subscription_trial','FOR UPDATE','subscription_trial_telegram_users','uq_one_trial_per_web_user','is_approved=true',"interval '10 days'",'SECURITY DEFINER','SET search_path','GRANT EXECUTE ON FUNCTION public.activate_subscription_trial']) assert.match(migration,new RegExp(x)); assert.match(migration,/REVOKE ALL ON FUNCTION public\.activate_subscription_trial[\s\S]*PUBLIC, anon, authenticated/); });
test('API keeps trial identity server-side and preserves the 12 endpoint boundary',()=>{ assert.equal(fs.readdirSync(path.join(root,'api')).filter(x=>x.endsWith('.js')).length,12); assert.match(api,/subscription-trial-status/);assert.match(api,/subscription-trial-activate/);assert.match(api,/idempotency_key/);assert.doesNotMatch(api,/email_otp|subscription-email/i); });
test('event allowlist accepts only primitive Phase 5A metadata',()=>{ assert.deepEqual(identity.safeEventMetadata('subscription_trial_activated',{request_id:'id',duration_days:10,token:'no'}),{request_id:'id',duration_days:10}); });
