'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path');
const identity=require('../lib/subscription-identity');
const migration=fs.readFileSync(path.join(__dirname,'..','supabase','subscription-phase-2-migration.sql'),'utf8');
test('link tokens are CSPRNG, HMAC-only, and expire after exactly five minutes',()=>{ process.env.TELEGRAM_SUBSCRIPTION_LINK_PEPPER='test-link-pepper-is-long-enough'; assert.equal(identity.LINK_TTL_MS,5*60*1000); const token=identity.createLinkToken(); assert.ok(token.length>30); assert.notEqual(identity.linkTokenHash(token),token); assert.match(identity.linkTokenHash(token),/^[a-f0-9]{64}$/); });
test('migration contains only Telegram subscription identity storage and durable idempotency',()=>{ for(const x of ['telegram_subscription_links','telegram_subscription_link_tokens','telegram_subscription_webhook_updates','consume_subscription_telegram_link','issue_subscription_telegram_link_token','SECURITY DEFINER','SET search_path','interval \'5 minutes\''])assert.match(migration,new RegExp(x)); assert.doesNotMatch(migration,/email_otp|EMAIL_OTP|email_verified|smtp|EMAIL_PROVIDER/i); assert.match(migration,/interval '10 days'/); });
test('token issuance revokes prior token and rate limits without plaintext storage',()=>{ assert.match(migration,/UPDATE public\.telegram_subscription_link_tokens SET revoked_at=now\(\)/); assert.match(migration,/interval '30 seconds'/); assert.match(migration,/token_hash text NOT NULL UNIQUE/); assert.match(migration,/used_at=now\(\)/); });
test('event metadata is narrow and never accepts secrets',()=>{ const x=identity.safeEventMetadata('subscription_telegram_link_rejected',{reason:'mismatch',token:'secret'}); assert.deepEqual(x,{reason:'mismatch'}); assert.throws(()=>identity.safeEventMetadata('unknown',{})); });
test('API has only Telegram Phase 4 actions and legacy verify webhook remains isolated',()=>{ assert.equal(fs.readdirSync(path.join(__dirname,'..','api')).filter(x=>x.endsWith('.js')).length,12); const source=fs.readFileSync(path.join(__dirname,'..','api','login-user.js'),'utf8'); assert.match(source,/subscription-telegram-webhook[\s\S]*telegram-verify-webhook/); assert.match(source,/TELEGRAM_SUBSCRIPTION_WEBHOOK_SECRET/); assert.match(source,/TELEGRAM_VERIFY_WEBHOOK_SECRET/); assert.doesNotMatch(source,/subscription-email|email_otp|EMAIL_OTP/i); assert.doesNotMatch(source,/delete\s+user/i); });
