'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'), vouchers=require('../lib/vouchers'), capability=require('../lib/subscription-capability'), bot=require('../lib/voucher-admin-bot'), sender=require('../lib/voucher-admin-sender'), identity=require('../lib/subscription-identity');
test('Phase 5C exact capabilities and fixed numeric owner authorization fail closed',async()=>{
 for(const v of [undefined,'','false','0','TRUE','yes']) assert.equal(capability.isVoucherAdminBotEnabled({SUBSCRIPTION_FEATURE_ENABLED:'true',VOUCHER_ADMIN_BOT_ENABLED:v}),false);
 assert.equal(capability.isVoucherAdminBotEnabled({SUBSCRIPTION_FEATURE_ENABLED:'true',VOUCHER_ADMIN_BOT_ENABLED:'true'}),true);
 assert.equal(vouchers.isVoucherAdminTelegramUser(6396446903),true); assert.equal(vouchers.isVoucherAdminTelegramUser('6396446903'),false); assert.equal(vouchers.isVoucherAdminTelegramUser(6396446904),false);
 assert.equal(bot.adminUpdate({update_id:1,message:{from:{id:6396446903,username:'x'},chat:{id:6396446903,type:'private'}}}).from.id,6396446903);
 for(const update of [{update_id:1,message:{from:{id:7},chat:{id:7,type:'private'}}},{update_id:1,message:{from:{id:6396446903},chat:{id:6396446903,type:'group'}}},{update_id:1,message:{from:{id:6396446903},chat:{id:2,type:'private'}}},{update_id:1,message:{from:{id:6396446903},chat:{id:6396446903,type:'private'},forward_sender_name:'no'}}]) assert.equal(bot.adminUpdate(update),null);
 assert.deepEqual(await capability.getVoucherAdminCapability(null,{SUBSCRIPTION_FEATURE_ENABLED:'true',VOUCHER_ADMIN_BOT_ENABLED:'true'}),{enabled:true,ready:false,reason:'unavailable'});
});
test('Phase 5C codes are CSPRNG AC codes, only safe hints are usable after delivery',()=>{process.env.VOUCHER_CODE_PEPPER='phase5c-test-pepper-long-enough';const codes=new Set(Array.from({length:20},()=>vouchers.generateVoucherCode()));assert.equal(codes.size,20);for(const code of codes){assert.match(code,/^AC-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{12}$/);assert.equal(vouchers.voucherCodeHash(code).length,64);assert.equal(vouchers.voucherCodeHint(code),code.slice(-4));}assert.equal(bot.validRef('VB-A1B2C3D4E5F6'),true);assert.equal(bot.validRef('code'),false);assert.equal(bot.CHUNK_SIZE,100);});
test('Phase 5C lifetime generation is independent of seven redemption seats and schema is unapplied',()=>{const migration=fs.readFileSync(path.join(root,'supabase','subscription-phase-5c-voucher-admin-migration.sql'),'utf8');for(const token of ['voucher_admin_sessions','voucher_batches','voucher_admin_webhook_updates','ENABLE ROW LEVEL SECURITY','REVOKE ALL','delivery_pending','claim_voucher_admin_webhook_update'])assert.match(migration,new RegExp(token));const requested=20,allocated=0;assert.equal(requested,20);assert.equal(7-allocated,7);assert.equal(allocated,0);});
test('Phase 5C event metadata allowlist strips plaintext and secrets',()=>{const out=identity.safeEventMetadata('voucher_batch_generated',{batch_reference:'VB-A1B2C3D4E5F6',generated_quantity:20,voucher_code:'AC-SECRET',code_hash:'secret',pepper:'secret'});assert.deepEqual(out,{batch_reference:'VB-A1B2C3D4E5F6',generated_quantity:20});assert.equal(sender.configured({SUBSCRIPTION_FEATURE_ENABLED:'true',VOUCHER_ADMIN_BOT_ENABLED:'true'}),false);});
