'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path');
const session=require('../lib/admin-session'); const auth=require('../lib/subscription-auth'); const ROOT=path.resolve(__dirname,'..');
function withSecret(fn){const old=process.env.SESSION_SECRET;process.env.SESSION_SECRET='phase-6a4-test-secret';return Promise.resolve().then(fn).finally(()=>{if(old===undefined)delete process.env.SESSION_SECRET;else process.env.SESSION_SECRET=old;});}
function request(username){const token=session.createSessionToken({userId:username==='budi'?'00000000-0000-4000-8000-000000000001':'00000000-0000-4000-8000-000000000002',username,isAdmin:username==='budi'});return{headers:{cookie:session.SESSION_COOKIE_NAME+'='+token}};}
function db(account,rows,rowError){return{from(table){if(table==='app_users')return{select(){return this;},eq(){return this;},maybeSingle(){return Promise.resolve({data:account,error:null});}};if(table==='user_entitlements')return{select(){return this;},eq(){return Promise.resolve({data:rows||[],error:rowError||null});}};throw new Error('unexpected table '+table);}};}
test('ordinary signed account without entitlement is Free and denied premium',async()=>withSecret(async()=>{const a={id:'00000000-0000-4000-8000-000000000002',username:'ujibot0720',is_blocked:false,is_approved:true};const access=await auth.resolvePremiumAccess(request('ujibot0720'),db(a,[]));assert.equal(access.ok,true);assert.equal(access.premium,false);assert.equal(access.access_level,'free');const denied=await auth.requirePremiumEntitlement(request('ujibot0720'),db(a,[]));assert.equal(denied.status,403);}));
test('active Trial and protected budi are premium',async()=>withSecret(async()=>{const now=Date.now();const a={id:'00000000-0000-4000-8000-000000000002',username:'ujibot0720',is_blocked:false,is_approved:true};const rows=[{plan_code:'TRIAL',source:'trial',status:'active',starts_at:new Date(now-1000).toISOString(),expires_at:new Date(now+86400000).toISOString(),lifetime:false}];assert.equal((await auth.requirePremiumEntitlement(request('ujibot0720'),db(a,rows))).premium,true);const b={id:'00000000-0000-4000-8000-000000000001',username:'budi',is_blocked:false,is_approved:true};assert.equal((await auth.requirePremiumEntitlement(request('budi'),db(b,[],{message:'missing'}))).access_level,'admin');}));
test('server premium reads use signed entitlement and preserve dedicated share and cron boundaries',()=>{const s=fs.readFileSync(path.join(ROOT,'api','sector-hot.js'),'utf8');assert.match(s,/requirePremiumEntitlement/);assert.match(s,/action === null[\s\S]*action === 'screener'[\s\S]*action === 'nk-screener-results'[\s\S]*action === 'daytrade-screener'/);assert.match(s,/premiumBrowserRead && !verifyCronSecret\(req\)/);assert.match(s,/action === 'public-screener-share'/);assert.doesNotMatch(s,/x-premium|x-access-level|x-subscription-plan/i);});
test('client hides premium navigation and guards direct route fail-closed',()=>{const h=fs.readFileSync(path.join(ROOT,'public','index.html'),'utf8');assert.match(h,/data-premium-nav=\"true\"/);assert.match(h,/premium-access-status/);assert.match(h,/hasConfirmedPremiumAccess/);assert.match(h,/Fitur ini tersedia untuk pengguna Trial dan Premium/);assert.match(h,/state:'unavailable',premium:false/);assert.match(h,/credentials:'same-origin'/);});
test('minimal status action exists and direct API file count stays 12',()=>{const s=fs.readFileSync(path.join(ROOT,'api','login-user.js'),'utf8');assert.match(s,/subscriptionAction === 'premium-access-status'/);assert.match(s,/resolvePremiumAccess\(req, db\)/);assert.equal(fs.readdirSync(path.join(ROOT,'api')).filter(n=>n.endsWith('.js')).length,12);});
