'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');
const env=require('../lib/runtime-env');const customer=require('../lib/telegram-membership-webhook');const customerBot=require('../lib/telegram-verify-bot');
const admin=require('../lib/telegram-admin-webhook');const adminService=require('../lib/telegram-admin-service');const membershipService=require('../lib/telegram-membership-service');
function response(){return{statusCode:0,body:null,status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}};}
function update(text,id=1){return{update_id:id,message:{text,from:{id:77},chat:{id:77,type:'private'}}};}
async function customerRun(text,db,id){const sent=[];const old=customerBot.sendMessage;customerBot.sendMessage=async(c,t,o)=>sent.push({c,t,o});try{return{outcome:await customer.processUpdate(update(text,id||Math.floor(Math.random()*100000)),db),sent};}finally{customerBot.sendMessage=old;}}
test('customer slash aliases, suffixes, text buttons, and unknown slash are routed safely',async()=>{
 const account={verified:true};const db={claimUpdate:async()=>true,account:async()=>account,packages:async()=>[],channelGrant:async()=>({grantId:'g'}),recordChannelInvite:async()=>{}};
 const aliases=[['/start','menu'],['/menu@auto_cuan_staging_bot','menu'],['/verifikasi','verify'],['/akun','account'],['/paket','packages'],['/beli','purchase'],['/voucher','purchase'],['/bantuan','help'],['/admin','admin'],['Akun Saya','account'],['Beli Paket','purchase']];
 for(let i=0;i<aliases.length;i++)assert.equal((await customerRun(aliases[i][0],db,100+i)).outcome,aliases[i][1]);
 const unknown=await customerRun('/tidak_ada CODE',db,999);assert.equal(unknown.outcome,'unknown_command');assert.match(unknown.sent[0].t,/tidak dikenal/);
});
test('/verifikasi CODE is extracted while raw codes remain outside membership routing',()=>{assert.equal(customer.verificationCodeFromCommand(update('/verifikasi@auto_cuan_staging_bot ABCD-EFGH')),'ABCD-EFGH');assert.equal(customer.isMembershipUpdate(update('ABCD-EFGH')),false);assert.equal(customer.verificationCodeFromCommand(update('/unknown ABCD-EFGH')),null);});
test('/voucher CODE PACKAGE uses server-owned purchase flow',async()=>{let call;const db={claimUpdate:async()=>true,account:async()=>({verified:true}),packageBySlug:async s=>({id:s}),createPurchase:async(...x)=>{call=x;return{finalAmount:1,bankInstructions:'bank',purchaseId:'p'};}};assert.equal((await customerRun('/voucher SAVE30 lifetime',db,201)).outcome,'voucher_purchase_created');assert.deepEqual(call,[77,'lifetime','SAVE30']);});
test('/channel alias keeps existing entitlement and invite authorization',async()=>{const oldInvite=customerBot.createChatInviteLink,oldChannel=process.env.TELEGRAM_VERIFY_CHANNEL_ID;customerBot.createChatInviteLink=async()=> 'https://t.me/+test';process.env.TELEGRAM_VERIFY_CHANNEL_ID='-100';const db={claimUpdate:async()=>true,account:async()=>({verified:true,entitlement:{status:'active',lifetime:false,endsAt:'2099-01-01'}}),channelGrant:async()=>({grantId:'g'}),recordChannelInvite:async()=>{}};try{assert.equal((await customerRun('/channel@auto_cuan_staging_bot',db,202)).outcome,'channel');}finally{customerBot.createChatInviteLink=oldInvite;if(oldChannel===undefined)delete process.env.TELEGRAM_VERIFY_CHANNEL_ID;else process.env.TELEGRAM_VERIFY_CHANNEL_ID=oldChannel;}});
test('staging admin configuration never falls back and normalizes username',()=>{const old={...process.env};try{process.env.AUTO_CUAN_ENV='staging';process.env.TELEGRAM_ADMIN_BOT_TOKEN='prod';process.env.TELEGRAM_ADMIN_WEBHOOK_SECRET='prod';process.env.TELEGRAM_ADMIN_BOT_USERNAME='@prod_bot';delete process.env.STAGING_TELEGRAM_ADMIN_BOT_TOKEN;delete process.env.STAGING_TELEGRAM_ADMIN_WEBHOOK_SECRET;delete process.env.STAGING_TELEGRAM_ADMIN_BOT_USERNAME;assert.throws(()=>env.adminTelegramConfig(),/admin_bot_configuration_missing/);process.env.STAGING_TELEGRAM_ADMIN_BOT_TOKEN='stage';process.env.STAGING_TELEGRAM_ADMIN_WEBHOOK_SECRET='secret';process.env.STAGING_TELEGRAM_ADMIN_BOT_USERNAME='@stage_bot';assert.deepEqual(env.adminTelegramConfig(),{token:'stage',webhookSecret:'secret',username:'stage_bot'});}finally{process.env=old;}});
test('admin webhook secret, size, and malformed protections fail closed',async()=>{const old={...process.env};process.env.AUTO_CUAN_ENV='staging';process.env.STAGING_TELEGRAM_ADMIN_BOT_TOKEN='t';process.env.STAGING_TELEGRAM_ADMIN_WEBHOOK_SECRET='s';process.env.STAGING_TELEGRAM_ADMIN_BOT_USERNAME='@b';try{for(const secret of [undefined,'wrong']){const r=response();await admin.handle({method:'POST',headers:{'x-telegram-bot-api-secret-token':secret},body:{update_id:1}},r,{});assert.equal(r.statusCode,401);}let r=response();await admin.handle({method:'POST',headers:{'x-telegram-bot-api-secret-token':'s','content-length':String(admin.MAX_BODY+1)},body:{update_id:1}},r,{});assert.equal(r.statusCode,413);r=response();await admin.handle({method:'POST',headers:{'x-telegram-bot-api-secret-token':'s'},body:{}},r,{});assert.equal(r.statusCode,200);assert.equal(r.body.ignored,true);}finally{process.env=old;}});
function deps(auth){const messages=[];return{messages,service:{UUID:adminService.UUID,authorize:async()=>auth,claimUpdate:async()=>true,releaseUpdate:async()=>true,pending:async()=>[],vouchers:async()=>[],audit:async()=>[],review:async()=>({})},bot:{sendMessage:async(c,t,o)=>messages.push({t,o}),answerCallbackQuery:async()=>{}},customerBot:{sendMessage:async()=>{}}};}
test('admin is private-only and unauthorized/revoked/blocked/unapproved contexts are generic',async()=>{let d=deps({authorized:true,user_id:'u'});assert.equal(await admin.processUpdate({update_id:1,message:{text:'/menu',from:{id:1},chat:{id:-1,type:'group'}}},d),'private_only');for(const context of [null,{authorized:false,reason:'revoked'},{authorized:false,blocked:true},{authorized:false,approved:false}]){d=deps(context);assert.equal(await admin.processUpdate(update('/menu',Math.random()),d),'unauthorized');assert.equal(d.messages[0].t,'Akses tidak tersedia.');}});
test('authorized budi commands, separate update claim, and sanitized outputs',async()=>{const d=deps({authorized:true,user_id:'admin'});d.service.pending=async()=>[{purchase_id:'123e4567-e89b-42d3-a456-426614174000',masked_username:'al****',package_name:'Lifetime',final_amount_idr:1,mime_type:'image/jpeg',file_size:10}];assert.equal(await admin.processUpdate(update('/pembayaran',10),d),'payments');assert.doesNotMatch(d.messages[0].t,/password|device|hash|pepper/i);assert.equal(d.messages[0].o.reply_markup.inline_keyboard[0][0].callback_data.length<65,true);});
test('voucher detail/list/deactivation, user lookup, and audit expose only sanitized fields',async()=>{const d=deps({authorized:true,user_id:'admin'});const voucher={id:'123e4567-e89b-42d3-a456-426614174000',code_hint:'SAVE…2026',discount_type:'fixed',discount_value:5000,package_slugs:'all',active:true,redemption_count:2};d.service.vouchers=async()=>[voucher];d.service.voucherDetail=async()=>voucher;d.service.deactivateVoucher=async()=>({already_inactive:true});d.service.userLookup=async()=>({masked_username:'al****',approved:true,blocked:false,telegram_verified:true,package_name:'Lifetime',lifetime:true,channel_access:true,dashboard_access:true});d.service.audit=async()=>[{created_at:'2026-01-01',event_type:'purchase_approved',purchase_id:voucher.id,metadata:{secret:'never-render'}}];const commands=['/voucher_daftar','/voucher_detail SAVE…2026','/voucher_nonaktifkan '+voucher.id,'/pengguna alice','/audit'];for(let i=0;i<commands.length;i++)await admin.processUpdate(update(commands[i],300+i),d);const rendered=d.messages.map(x=>x.t).join('\n');assert.doesNotMatch(rendered,/code_hash|password|device|pepper|secret|metadata/i);assert.match(rendered,/sudah nonaktif/);});
test('approval, duplicate retry, rejection, and customer notification are best effort',async()=>{for(const decision of ['approve','reject']){const d=deps({authorized:true,user_id:'admin'});d.service.review=async()=>({approved:decision==='approve',duplicate:false,customer_chat_id:9,package_name:'Lifetime',lifetime:true});d.customerBot.sendMessage=async()=>{throw new Error('down');};const u={update_id:decision==='approve'?11:12,callback_query:{id:'cb',data:decision+':123e4567-e89b-42d3-a456-426614174000',from:{id:77},message:{chat:{id:77,type:'private'}}}};assert.equal(await admin.processUpdate(u,d),decision==='approve'?'approved':'rejected');}const d=deps({authorized:true,user_id:'admin'});d.service.claimUpdate=async()=>false;assert.equal(await admin.processUpdate(update('/menu',11),d),'duplicate');});
test('voucher creation hashes code, never sends raw code to RPC, and sanitized render omits hash',async()=>{const old=process.env.VOUCHER_CODE_PEPPER;process.env.VOUCHER_CODE_PEPPER='test-pepper';let args;try{await adminService.createVoucher({code:'SAVE-2026',type:'percent',value:30,package:'all',limit:0,days:0},'u',async(name,a)=>{args=a;return{id:'x'};});assert.equal(args.p_code_hash.length,64);assert.equal(JSON.stringify(args).includes('SAVE2026'),false);const text=admin.voucherText({id:'12345678-x',code_hint:'SAVE…2026',discount_type:'percent',discount_value:30,active:true});assert.doesNotMatch(text,/hash|pepper/i);}finally{if(old===undefined)delete process.env.VOUCHER_CODE_PEPPER;else process.env.VOUCHER_CODE_PEPPER=old;}});
test('proof notification is durable, media/text best effort, and does not throw',async()=>{let media=0,text=0;const deps={adminService:{notificationTargets:async()=>[{private_chat_id:1}],releaseNotification:async()=>{}},verifyBot:{downloadFile:async()=>Buffer.from('x')},adminBot:{sendBytes:async()=>{media++;throw new Error('fail');},sendMessage:async()=>{text++;}}};assert.equal(await membershipService.notifyAdminsOfProof({purchaseId:'123e4567-e89b-42d3-a456-426614174000',notificationText:'safe'},{fileId:'f',mimeType:'image/jpeg'},deps),true);assert.equal(media,1);assert.equal(text,1);deps.adminService.notificationTargets=async()=>[];assert.equal(await membershipService.notifyAdminsOfProof({purchaseId:'123e4567-e89b-42d3-a456-426614174000'},{},deps),false);});
test('migration isolates updates, RLS/RPCs, raw voucher secrets, and service role grants',()=>{const sql=fs.readFileSync('supabase/telegram-admin-bot-v1-migration.sql','utf8');assert.match(sql,/membership_admin_bot_processed_updates/);assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/SECURITY DEFINER[\s\S]*SET search_path=pg_catalog,public/);assert.match(sql,/REVOKE ALL[\s\S]*PUBLIC,anon,authenticated/);assert.match(sql,/GRANT[\s\S]*service_role/);assert.doesNotMatch(sql,/raw_code|voucher_pepper|password_hash|device_id/);});
