'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../public/viewport-runtime.js'),'utf8');
function target(values={}){const callbacks=new Map();return Object.assign(values,{addEventListener(name,fn){const list=callbacks.get(name)||[];list.push(fn);callbacks.set(name,list);},dispatchEvent(e){for(const fn of callbacks.get(e.type)||[])fn(e);},count:name=>(callbacks.get(name)||[]).length});}
function setup(hasViewport=true){
 const styles=new Map(),classes=new Set(),frames=new Map();let next=1,writes=0,events=0;
 const html={clientWidth:390,clientHeight:844,style:{setProperty(k,v){writes++;styles.set(k,v);}},classList:{contains:n=>classes.has(n),toggle(n,v){v?classes.add(n):classes.delete(n);}}};
 const doc=target({documentElement:html,body:{},hidden:false,activeElement:null});doc.addEventListener('autocuan:viewportchange',()=>events++);
 const vv=target({height:844,width:390,scale:1,offsetTop:0,offsetLeft:0});
 const win=target({document:doc,innerWidth:390,innerHeight:844,visualViewport:hasViewport?vv:undefined,requestAnimationFrame(fn){const id=next++;frames.set(id,fn);return id;},cancelAnimationFrame(id){frames.delete(id);},scrollBy(){throw new Error('Unexpected forced scroll');},getComputedStyle(){return {overflowY:'visible'};}});
 const context=vm.createContext({window:win,WeakSet,Map,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},Object});const run=()=>vm.runInContext(source,context);run();
 const flush=()=>{const jobs=[...frames.values()];frames.clear();jobs.forEach(fn=>fn());};
 const focus=()=>{doc.activeElement={tagName:'INPUT',type:'text',disabled:false,readOnly:false,isConnected:false,closest:()=>null};doc.dispatchEvent({type:'focusin',target:doc.activeElement});flush();};
 const geometry=data=>{Object.assign(vv,data);vv.dispatchEvent({type:'resize'});flush();};
 return {win,doc,vv,html,styles,classes,frames,run,flush,focus,geometry,counts:()=>({writes,events})};
}
test('viewport has one owner and frozen snapshots',()=>{const x=setup(),api=x.win.AutoCuanViewport;x.run();assert.equal(x.win.AutoCuanViewport,api);assert.equal(x.doc.count('focusin'),1);assert.equal(x.vv.count('resize'),1);assert.ok(Object.isFrozen(api.snapshot()));});
test('visual-only keyboard uses panning offset without resizing the document',()=>{const x=setup();x.focus();x.geometry({height:330,offsetTop:45});const s=x.win.AutoCuanViewport.snapshot();assert.equal(s.keyboard,true);assert.equal(s.keyboardGap,469);assert.equal(x.styles.get('--ac-vv-top'),'45px');assert.equal(x.styles.get('--ac-vv-height'),'330px');assert.equal(x.win.innerHeight,844);x.geometry({height:844,offsetTop:0});assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,false);});
test('layout-resizing keyboard does not add duplicate keyboard padding',()=>{const x=setup();x.focus();x.win.innerHeight=360;x.html.clientHeight=360;x.geometry({height:360});assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,true);assert.equal(x.win.AutoCuanViewport.snapshot().keyboardGap,0);});
test('zoom, unfocused page and ordinary browser chrome are not treated as keyboard',()=>{const x=setup();x.geometry({height:350});assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,false);x.focus();x.geometry({height:350,scale:2});assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,false);x.geometry({height:800,scale:1});assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,false);});
test('resize bursts coalesce and unchanged geometry avoids root DOM writes',()=>{const x=setup(),start=x.counts();for(let n=0;n<100;n++)x.vv.dispatchEvent({type:'resize'});assert.equal(x.frames.size,1);x.flush();assert.deepEqual(x.counts(),start);x.geometry({offsetTop:1});assert.equal(x.counts().events,start.events+1);assert.equal(x.counts().writes,start.writes+1);});
test('IME guards explicit composition, Android legacy code and composition lifecycle',()=>{const x=setup(),node={},composing=x.win.AutoCuanViewport.isComposing;assert.equal(composing({target:node}),false);assert.equal(composing({target:node,isComposing:true}),true);assert.equal(composing({target:node,keyCode:229}),true);x.doc.dispatchEvent({type:'compositionstart',target:node});assert.equal(composing({target:node}),true);x.doc.dispatchEvent({type:'compositionend',target:node});assert.equal(composing({target:node}),false);});
test('fallback supports layout changes and lifecycle restoration without VisualViewport',()=>{const x=setup(false);x.focus();x.win.innerHeight=350;x.win.dispatchEvent({type:'resize'});x.flush();assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,true);x.win.dispatchEvent({type:'resize'});x.doc.hidden=true;x.doc.dispatchEvent({type:'visibilitychange'});assert.equal(x.frames.size,0);x.doc.activeElement=null;x.doc.hidden=false;x.win.innerHeight=844;x.doc.dispatchEvent({type:'visibilitychange'});x.flush();assert.equal(x.win.AutoCuanViewport.snapshot().keyboard,false);});
test('entrypoints share viewport runtime and preserve zoom',()=>{for(const name of ['index.html','register.html','analisis-saham.html','portfolio-command-center.html']){const s=fs.readFileSync(path.join(__dirname,'../public',name),'utf8');assert.match(s,/viewport-runtime\.js/);assert.match(s,/viewport\.css/);assert.doesNotMatch(s,/user-scalable\s*=\s*(?:no|0)|maximum-scale\s*=\s*1/);}});
