'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
test('self-hosted NumberFlow distribution matches the committed provenance',()=>{const p='public/vendor/number-flow-0.6.2/',m=JSON.parse(read(p+'PROVENANCE.json'));assert.equal(m.version,'0.6.2');assert.equal(m.license,'MIT');for(const [file,sha]of Object.entries(m.files)){assert.equal(crypto.createHash('sha256').update(read(p+file)).digest('hex'),sha,file);}assert.match(read(p+'index.mjs'),/l\("number-flow", b\)/);});
test('numeric rendering is progressive and does not synthesize interim finance data',()=>{const s=read('public/number-flow-runtime.js');assert.match(s,/aria-hidden/);assert.match(s,/record.text.textContent=text/);assert.match(s,/prefers-reduced-motion/);assert.match(s,/flow\.update\(record\.value\)/);assert.doesNotMatch(s,/setInterval|requestAnimationFrame|Math\.random/);});
test('worksheet dependency order is deterministic',()=>{const html=read('public/money-sheet-lazy-loader.js');let prev=0;for(const file of ['money-sheet-formulas.js','money-sheet-model.js','money-sheet-grid.js','money-sheet-runtime.js']){const at=html.indexOf('/'+file);assert.ok(at>prev,file);prev=at;}});
test('new setup refuses unknown account schemas before creating any table',()=>{const sql=read('supabase/money-sheet-setup.sql');assert.ok(sql.indexOf("to_regclass('public.app_users')")<sql.indexOf('CREATE TABLE'));assert.match(sql,/udt_name='uuid'/);assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/REVOKE ALL.*PUBLIC, anon, authenticated/);assert.match(sql,/sheet_revision/);assert.doesNotMatch(sql,/DROP TABLE|DELETE FROM|DISABLE ROW LEVEL|CREATE TABLE(?: IF NOT EXISTS)? public\.app_users/i);assert.match(sql,/BEGIN;[\s\S]*COMMIT;/);});
test('existing additive migration is unchanged in purpose and kept separately',()=>{assert.match(read('supabase/money-sheet-v1-migration.sql'),/ALTER TABLE public.user_personal_cashflow/);assert.doesNotMatch(read('supabase/money-sheet-v1-migration.sql'),/CREATE TABLE/i);});
test('source values distinguish unavailable from zero, and never infer signals by rank',()=>{const html=read('public/index.html');const s=html.slice(html.indexOf('function loadLandingShowcase'),html.indexOf('function openAuthChoiceModal'));assert.match(s,/Number\.isFinite/);assert.match(s,/Belum tersedia/);assert.match(s,/AutoCuanNumeric/);assert.doesNotMatch(s,/idx\s*===?\s*0\s*\?\s*['"]Entry/);});
