"""
Auto-Cuan: AI Chart Reader Backend
Secure Flask server for Gemini Vision API integration.
"""

import os
import json
import base64
import requests
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS

app = Flask(__name__, static_folder='.', static_url_path='')
CORS(app)

# --- Secure API Key Configuration ---
# Fetches from environment variable first; falls back to local config for dev.
GEMINI_API_KEY = os.environ.get(
    'GEMINI_API_KEY',
    'AIzaSyCxTB2KMrTGKkENIBM8bbcZf65cOknFoDY'
)

# Gemini 2.5 Flash endpoint
GEMINI_MODEL = 'gemini-2.5-flash'
GEMINI_API_URL = f'https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent'

# --- Expert SMC Prompt (Indonesian) ---
SYSTEM_PROMPT = """Anda adalah AI Analis Teknikal Saham Profesional Khusus Market Structure dan Smart Money Concepts (SMC). Tugas Anda adalah menganalisis gambar screenshot chart saham yang dikirimkan oleh pengguna secara mendalam dan 100% akurat sesuai visual gambar.

1. Periksa gambar dengan teliti, cari posisi harga terakhir, area Liquidity/Fair Value Gap (FVG), zona Order Block (Demand/Supply), serta sinyal perubahan karakter tren seperti CHoCH, BOS, atau MSB dari indikator LuxAlgo yang ada pada gambar.

2. Di bagian atas hasil analisis, tampilkan rangkuman kondisi pasar saat ini (Bullish/Bearish/Sideways) beserta teks penjelasan teknikal detail dalam Bahasa Indonesia mengenai mengapa tren tersebut terjadi berdasarkan bukti visual chart asli tersebut.

3. Buatlah tabel HTML responsif menggunakan styling Tailwind CSS yang memuat 3 Opsi Trading Plan Manajemen Risiko:
   - OPSI 1 (AGRESIF - PILIHAN TERBAIK): Entry, Stop Loss (SL), Take Profit (TP), dan Rasio Risk:Reward (RR) berdasarkan breakout terdekat.
   - OPSI 2 (KONSERVATIF): Entry, SL, TP, dan Rasio RR berdasarkan area koreksi pullback ke zona Order Block terkuat.
   - OPSI 3 (FAST SCALPING): Entry, SL, TP, dengan Rasio Risk:Reward wajib diatur pas 1 : 1.0.

4. Pastikan semua angka nominal harga (Rp) pada tabel disesuaikan dengan skala harga saham asli yang terlihat pada sumbu kanan gambar chart. Jangan berikan angka palsu, statis, atau templat acak.

Format seluruh output dalam HTML yang valid dengan styling Tailwind CSS agar bisa langsung di-render di browser. Gunakan warna teks terang (putih/hijau/merah) agar kontras dengan background gelap (#0b0e14)."""


@app.route('/')
def serve_index():
    """Serve the frontend."""
    return send_from_directory('.', 'index.html')


@app.route('/api/analyze', methods=['POST'])
def analyze_chart():
    """
    Secure POST endpoint that receives chart image from frontend,
    attaches Gemini API key server-side, and forwards to Google API.
    """
    try:
        data = request.get_json()

        if not data or 'image' not in data:
            return jsonify({'error': 'No image data provided.'}), 400

        image_data = data['image']
        mime_type = data.get('mimeType', 'image/png')

        # Remove data URI prefix if present
        if ',' in image_data:
            image_data = image_data.split(',')[1]

        # Build Gemini API request payload
        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": SYSTEM_PROMPT
                        },
                        {
                            "inline_data": {
                                "mime_type": mime_type,
                                "data": image_data
                            }
                        }
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.7,
                "topP": 0.95,
                "topK": 40,
                "maxOutputTokens": 8192
            }
        }

        # Forward request to Gemini API (key stays server-side)
        response = requests.post(
            f'{GEMINI_API_URL}?key={GEMINI_API_KEY}',
            headers={'Content-Type': 'application/json'},
            json=payload,
            timeout=120
        )

        if response.status_code != 200:
            error_detail = response.json() if response.content else {}
            return jsonify({
                'error': f'Gemini API error ({response.status_code})',
                'detail': error_detail
            }), response.status_code

        result = response.json()

        # Extract generated text from response
        candidates = result.get('candidates', [])
        if candidates:
            content = candidates[0].get('content', {})
            parts = content.get('parts', [])
            if parts:
                analysis_html = parts[0].get('text', '')
                return jsonify({'html': analysis_html})

        return jsonify({'error': 'No analysis generated by the model.'}), 500

    except requests.exceptions.Timeout:
        return jsonify({'error': 'Request to Gemini API timed out. Please try again.'}), 504
    except Exception as e:
        return jsonify({'error': f'Server error: {str(e)}'}), 500


@app.route('/api/news', methods=['GET'])
def get_yahoo_news():
    """
    Proxy endpoint to fetch Yahoo Finance news for Indonesian stocks.
    Query param: ?q=BBCA (ticker symbol)
    """
    query = request.args.get('q', 'IHSG saham indonesia')

    try:
        # Yahoo Finance RSS feed for news
        yahoo_url = f'https://news.google.com/rss/search?q={query}+saham+indonesia&hl=id&gl=ID&ceid=ID:id'

        response = requests.get(yahoo_url, timeout=10, headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })

        if response.status_code == 200:
            import xml.etree.ElementTree as ET
            root = ET.fromstring(response.content)
            channel = root.find('channel')
            items = channel.findall('item') if channel is not None else []

            news_list = []
            for item in items[:8]:
                title = item.find('title')
                link = item.find('link')
                pub_date = item.find('pubDate')
                news_list.append({
                    'title': title.text if title is not None else '',
                    'link': link.text if link is not None else '',
                    'pubDate': pub_date.text if pub_date is not None else ''
                })

            return jsonify({'news': news_list})

        return jsonify({'news': [], 'error': 'Failed to fetch news'}), 200

    except Exception as e:
        return jsonify({'news': [], 'error': str(e)}), 200


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f"\n{'='*50}")
    print(f"  Auto-Cuan AI Chart Reader")
    print(f"  Running on http://localhost:{port}")
    print(f"  Gemini Model: {GEMINI_MODEL}")
    print(f"  API Key: {'*' * 20}...{GEMINI_API_KEY[-4:]}")
    print(f"{'='*50}\n")
    app.run(host='0.0.0.0', port=port, debug=True)
