'use strict';
// Server-only voucher boundary. Plaintext codes never leave the creation call.
const crypto = require('crypto');
const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const TYPES = new Set(['PERCENT_30','PERCENT_50','PERCENT_100','LIFETIME']);
const PLANS = new Set(['PREMIUM_1_MONTH','PREMIUM_2_MONTHS','PREMIUM_3_MONTHS','LIFETIME']);
function pepper() { if (!process.env.VOUCHER_CODE_PEPPER) throw new Error('voucher unavailable'); return process.env.VOUCHER_CODE_PEPPER; }
function normalizeCode(value) { if (typeof value !== 'string') return ''; return value.trim().toUpperCase().replace(/[\s_-]/g,''); }
function generateCode() { let out='AC-'; for(let i=0;i<20;i++) out += ALPHABET[crypto.randomInt(ALPHABET.length)]; return out; }
function hashCode(code) { const n=normalizeCode(code); if (!n || n.length > 80) throw new Error('voucher unavailable'); return crypto.createHmac('sha256',pepper()).update(n,'utf8').digest('hex'); }
function codeHint(code) { const n=normalizeCode(code); return 'AC-••••' + n.slice(-4); }
function safeVoucher(v) { return { reference:v.id, code_hint:v.code_hint, voucher_type:v.voucher_type, allowed_plan_codes:v.allowed_plan_codes, starts_at:v.starts_at, ends_at:v.ends_at, max_redemptions:v.max_redemptions, per_user_limit:v.per_user_limit, redemption_count:v.redemption_count, enabled:v.enabled === true, created_at:v.created_at, disabled_at:v.disabled_at || null, disable_reason:v.disable_reason || null, creator:'admin' }; }
function parseCreate(input) { input=input||{}; const type=String(input.voucher_type||''); const plans=Array.isArray(input.allowed_plan_codes)?[...new Set(input.allowed_plan_codes.map(String))]:[]; if(!TYPES.has(type)||!plans.length||plans.some(x=>!PLANS.has(x))) throw new Error('Voucher tidak valid.'); if((type==='LIFETIME') !== (plans.length===1&&plans[0]==='LIFETIME')) throw new Error('Paket voucher tidak valid.'); if(type!=='LIFETIME' && plans.includes('LIFETIME')) throw new Error('Paket voucher tidak valid.'); const starts=new Date(input.starts_at||Date.now()); const ends=input.ends_at?new Date(input.ends_at):null; if(!Number.isFinite(+starts)||(ends&&!Number.isFinite(+ends))||(ends&&ends<=starts)) throw new Error('Periode voucher tidak valid.'); const limit=(v,name)=>v==null||v===''?null:(Number.isSafeInteger(Number(v))&&Number(v)>0?Number(v):(()=>{throw new Error(name+' tidak valid.');})()); return {voucher_type:type,allowed_plan_codes:plans,starts_at:starts.toISOString(),ends_at:ends&&ends.toISOString(),max_redemptions:limit(input.max_redemptions,'Batas global'),per_user_limit:limit(input.per_user_limit,'Batas pengguna')}; }
async function createVoucher(db, actorId, input) { const data=parseCreate(input), plaintext=generateCode(); const row=Object.assign({},data,{code_hash:hashCode(plaintext),code_hint:codeHint(plaintext),created_by_user_id:actorId}); const r=await db.from('vouchers').insert(row).select('id,code_hint,voucher_type,allowed_plan_codes,starts_at,ends_at,max_redemptions,per_user_limit,redemption_count,enabled,created_at,disabled_at,disable_reason').single(); if(r.error) throw new Error('Voucher tidak dapat dibuat.'); await db.from('subscription_events').insert({actor_user_id:actorId,event_type:'subscription_voucher_created',metadata:{voucher_reference:r.data.id,code_hint:r.data.code_hint,voucher_type:r.data.voucher_type,source_channel:'admin_web'}}); return {voucher:safeVoucher(r.data), plaintext_code:plaintext}; }
function discount(type, price) { return type==='PERCENT_30'?Math.floor(price*70/100):type==='PERCENT_50'?Math.floor(price/2):0; }
async function quoteVoucher(db, account, input) { if(String(account.username).toLowerCase()==='budi') return {admin:true,requires_payment:false}; if(account.is_blocked) throw new Error('unavailable'); const plan=String(input&&input.plan_code||''); if(!PLANS.has(plan)) throw new Error('unavailable'); const hash=hashCode(input&&input.code); const v=await db.from('vouchers').select('*').eq('code_hash',hash).maybeSingle(); const now=Date.now(); if(v.error||!v.data||!v.data.enabled||new Date(v.data.starts_at)>now||(v.data.ends_at&&new Date(v.data.ends_at)<=now)||!v.data.allowed_plan_codes.includes(plan)||(v.data.max_redemptions!=null&&v.data.redemption_count>=v.data.max_redemptions)) throw new Error('unavailable'); const used=await db.from('voucher_redemptions').select('id',{count:'exact',head:true}).eq('voucher_id',v.data.id).eq('user_id',account.id).in('status',['pending_payment','activated']); if(used.error||(v.data.per_user_limit!=null&&used.count>=v.data.per_user_limit)) throw new Error('unavailable'); const p=await db.from('subscription_plan_prices').select('normal_price_idr,promo_price_idr,promo_enabled,promo_starts_at,promo_ends_at').eq('plan_code',plan).eq('active',true).maybeSingle(); if(p.error||!p.data) throw new Error('unavailable'); const base=(p.data.promo_enabled&&p.data.promo_price_idr&&new Date(p.data.promo_starts_at)<=now&&(!p.data.promo_ends_at||new Date(p.data.promo_ends_at)>now))?p.data.promo_price_idr:p.data.normal_price_idr; const final=discount(v.data.voucher_type,Number(base)); return {selected_plan:plan,voucher_type:v.data.voucher_type,normal_price_idr:Number(base),final_price_idr:final,requires_payment:final>0,expires_at:v.data.ends_at||null}; }
module.exports={normalizeCode,generateCode,hashCode,codeHint,safeVoucher,parseCreate,createVoucher,quoteVoucher,discount};
