/**
 * Auto-Cuan: Vercel Serverless Function - Chart Analysis
 * Securely proxies chart image to Google Gemini 2.5 Flash API.
 * API key is read from process.env.GEMINI_API_KEY (never exposed to client).
 */

export const config = {
  maxDuration: 120,
};

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const GEMINI_MODEL = 'gemini-2.5-flash';
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

const SYSTEM_PROMPT = `Anda adalah AI Analis Teknikal Saham Profesional Khusus Market Structure dan Smart Money Concepts (SMC). Tugas Anda adalah menganalisis gambar screenshot chart saham yang dikirimkan oleh pengguna secara mendalam dan 100% akurat sesuai visual gambar.

1. Periksa gambar dengan teliti, cari posisi harga terakhir, area Liquidity/Fair Value Gap (FVG), zona Order Block (Demand/Supply), serta sinyal perubahan karakter tren seperti CHoCH, BOS, atau MSB dari indikator LuxAlgo yang ada pada gambar.

2. Di bagian atas hasil analisis, tampilkan rangkuman kondisi pasar saat ini (Bullish/Bearish/Sideways) beserta teks penjelasan teknikal detail dalam Bahasa Indonesia mengenai mengapa tren tersebut terjadi berdasarkan bukti visual chart asli tersebut.

3. Buatlah tabel HTML responsif menggunakan styling Tailwind CSS yang memuat 3 Opsi Trading Plan Manajemen Risiko:
   - OPSI 1 (AGRESIF - PILIHAN TERBAIK): Entry, Stop Loss (SL), Take Profit (TP), dan Rasio Risk:Reward (RR) berdasarkan breakout terdekat.
   - OPSI 2 (KONSERVATIF): Entry, SL, TP, dan Rasio RR berdasarkan area koreksi pullback ke zona Order Block terkuat.
   - OPSI 3 (FAST SCALPING): Entry, SL, TP, dengan Rasio Risk:Reward wajib diatur pas 1 : 1.0.

4. Pastikan semua angka nominal harga (Rp) pada tabel disesuaikan dengan skala harga saham asli yang terlihat pada sumbu kanan gambar chart. Jangan berikan angka palsu, statis, atau templat acak.

Format seluruh output dalam HTML yang valid dengan styling Tailwind CSS agar bisa langsung di-render di browser. Gunakan warna teks terang (putih/hijau/merah) agar kontras dengan background gelap (#0b0e14).`;

export default async function handler(req, res) {
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Validate API key is configured
  if (!GEMINI_API_KEY) {
    return res.status(500).json({ error: 'GEMINI_API_KEY is not configured on the server.' });
  }

  try {
    const { image, mimeType } = req.body;

    if (!image) {
      return res.status(400).json({ error: 'No image data provided.' });
    }

    // Strip data URI prefix if present (e.g. "data:image/png;base64,...")
    let imageData = image;
    if (imageData.includes(',')) {
      imageData = imageData.split(',')[1];
    }

    const mime = mimeType || 'image/png';

    // Build Gemini API payload
    const payload = {
      contents: [
        {
          parts: [
            { text: SYSTEM_PROMPT },
            {
              inline_data: {
                mime_type: mime,
                data: imageData,
              },
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.7,
        topP: 0.95,
        topK: 40,
        maxOutputTokens: 8192,
      },
    };

    // Call Gemini API — key stays server-side
    const geminiRes = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!geminiRes.ok) {
      const errBody = await geminiRes.json().catch(() => ({}));
      return res.status(geminiRes.status).json({
        error: `Gemini API error (${geminiRes.status})`,
        detail: errBody,
      });
    }

    const result = await geminiRes.json();

    // Extract generated HTML text
    const candidates = result.candidates || [];
    if (candidates.length > 0) {
      const parts = candidates[0]?.content?.parts || [];
      if (parts.length > 0) {
        return res.status(200).json({ html: parts[0].text || '' });
      }
    }

    return res.status(500).json({ error: 'No analysis generated by the model.' });
  } catch (error) {
    console.error('analyze error:', error);
    return res.status(500).json({ error: `Server error: ${error.message}` });
  }
}
