\set ON_ERROR_STOP on
DO $$
DECLARE b uuid; c jsonb; r jsonb; a uuid; t uuid; items jsonb; rows_before bigint; refs_before text[]; hashes_before text[]; hints_before text[]; batch_generated bigint; batch_status text; chunk_generated integer; chunk_status text; current_attempt uuid; attempt_stored integer; attempt_status text; attempt_time timestamptz; indexes_before bigint[]; active_before boolean[]; pending_before boolean[]; progress_before bigint; result_before text; changed_hash_rejected boolean := false; changed_hint_rejected boolean := false; extra_key_rejected boolean := false;
BEGIN
 SELECT id INTO b FROM public.app_users WHERE username='budi';
 INSERT INTO public.voucher_batches(id,batch_reference,actor_user_id,voucher_type,plan_code,requested_quantity,confirmation_key) VALUES(gen_random_uuid(),'VB-C1D2E3F4A5B6',b,'PERCENT_100','PREMIUM_1_MONTH',2,'22222222-2222-4222-8222-222222222222');
 c:=public.claim_voucher_admin_batch_chunk('VB-C1D2E3F4A5B6'); a:=(c->>'attempt_id')::uuid; t:=(c->>'claim_token')::uuid;
 items:=jsonb_build_array(jsonb_build_object('code_hash',repeat('c',64),'code_hint','C1D2'),jsonb_build_object('code_hash',repeat('d',64),'code_hint','E3F4'));
 r:=public.prepare_voucher_admin_batch_chunk('VB-C1D2E3F4A5B6',0,a,t,items);
 SELECT count(*),array_agg(voucher_reference ORDER BY item_index),array_agg(code_hash ORDER BY item_index),array_agg(code_hint ORDER BY item_index),array_agg(item_index ORDER BY item_index),array_agg(active ORDER BY item_index),array_agg(delivery_pending ORDER BY item_index) INTO rows_before,refs_before,hashes_before,hints_before,indexes_before,active_before,pending_before FROM public.subscription_vouchers WHERE attempt_id=a;
 SELECT generated_quantity,status,progress_cursor INTO batch_generated,batch_status,progress_before FROM public.voucher_batches WHERE batch_reference='VB-C1D2E3F4A5B6'; SELECT generated_count,status,current_attempt_id INTO chunk_generated,chunk_status,current_attempt FROM public.voucher_batch_chunks WHERE batch_id=(SELECT id FROM public.voucher_batches WHERE batch_reference='VB-C1D2E3F4A5B6'); SELECT stored_count,status,prepared_at,last_safe_result_code INTO attempt_stored,attempt_status,attempt_time,result_before FROM public.voucher_batch_chunk_attempts WHERE id=a;
 r:=public.prepare_voucher_admin_batch_chunk('VB-C1D2E3F4A5B6',0,a,t,items);
 IF r->>'prepared'<>'true' OR r->>'already_prepared'<>'true' OR r->>'safe_result_code'<>'already_prepared' OR (r->>'stored_count')::integer<>2 OR (r->>'expected_count')::integer<>2 OR (r->>'chunk_index')::integer<>0 OR (r->>'attempt_id')::uuid<>a THEN RAISE EXCEPTION 'exact replay assertion failed'; END IF;
 IF (SELECT count(*) FROM public.subscription_vouchers WHERE attempt_id=a)<>rows_before OR (SELECT array_agg(voucher_reference ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM refs_before OR (SELECT array_agg(code_hash ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM hashes_before OR (SELECT array_agg(code_hint ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM hints_before OR (SELECT generated_quantity FROM public.voucher_batches WHERE batch_reference='VB-C1D2E3F4A5B6')<>batch_generated OR (SELECT generated_count FROM public.voucher_batch_chunks WHERE current_attempt_id=a)<>chunk_generated OR (SELECT stored_count FROM public.voucher_batch_chunk_attempts WHERE id=a)<>attempt_stored OR (SELECT prepared_at FROM public.voucher_batch_chunk_attempts WHERE id=a)<>attempt_time THEN RAISE EXCEPTION 'exact replay mutated state'; END IF;
 BEGIN PERFORM public.prepare_voucher_admin_batch_chunk('VB-C1D2E3F4A5B6',0,a,t,jsonb_build_array(jsonb_build_object('code_hash',repeat('e',64),'code_hint','C1D2'),jsonb_build_object('code_hash',repeat('d',64),'code_hint','E3F4'))); RAISE EXCEPTION 'changed-hash replay accepted'; EXCEPTION WHEN others THEN IF SQLERRM<>'conflicting replay' THEN RAISE; END IF; changed_hash_rejected:=true; END; IF NOT changed_hash_rejected THEN RAISE EXCEPTION 'changed-hash rejection missing'; END IF;
 BEGIN PERFORM public.prepare_voucher_admin_batch_chunk('VB-C1D2E3F4A5B6',0,a,t,jsonb_build_array(jsonb_build_object('code_hash',repeat('c',64),'code_hint','Z9Y8'),jsonb_build_object('code_hash',repeat('d',64),'code_hint','E3F4'))); RAISE EXCEPTION 'changed-hint replay accepted'; EXCEPTION WHEN others THEN IF SQLERRM<>'conflicting replay' THEN RAISE; END IF; changed_hint_rejected:=true; END; IF NOT changed_hint_rejected THEN RAISE EXCEPTION 'changed-hint rejection missing'; END IF;
 BEGIN PERFORM public.prepare_voucher_admin_batch_chunk('VB-C1D2E3F4A5B6',0,a,t,jsonb_build_array(jsonb_build_object('code_hash',repeat('c',64),'code_hint','C1D2','plaintext','forbidden'),jsonb_build_object('code_hash',repeat('d',64),'code_hint','E3F4'))); RAISE EXCEPTION 'extra-key replay accepted'; EXCEPTION WHEN others THEN IF SQLERRM<>'voucher unavailable' THEN RAISE; END IF; extra_key_rejected:=true; END; IF NOT extra_key_rejected THEN RAISE EXCEPTION 'extra-key rejection missing'; END IF;
 IF (SELECT count(*) FROM public.subscription_vouchers WHERE attempt_id=a)<>rows_before OR (SELECT array_agg(voucher_reference ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM refs_before OR (SELECT array_agg(code_hash ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM hashes_before OR (SELECT array_agg(code_hint ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM hints_before OR (SELECT array_agg(item_index ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM indexes_before OR (SELECT array_agg(active ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM active_before OR (SELECT array_agg(delivery_pending ORDER BY item_index) FROM public.subscription_vouchers WHERE attempt_id=a) IS DISTINCT FROM pending_before OR (SELECT generated_quantity FROM public.voucher_batches WHERE batch_reference='VB-C1D2E3F4A5B6')<>batch_generated OR (SELECT progress_cursor FROM public.voucher_batches WHERE batch_reference='VB-C1D2E3F4A5B6')<>progress_before OR (SELECT generated_count FROM public.voucher_batch_chunks WHERE current_attempt_id=a)<>chunk_generated OR (SELECT stored_count FROM public.voucher_batch_chunk_attempts WHERE id=a)<>attempt_stored OR (SELECT prepared_at FROM public.voucher_batch_chunk_attempts WHERE id=a)<>attempt_time OR (SELECT last_safe_result_code FROM public.voucher_batch_chunk_attempts WHERE id=a) IS DISTINCT FROM result_before THEN RAISE EXCEPTION 'rejected replay mutated state'; END IF;
END $$;
